version: '3'

services:
  restic-pg-dump:
    build: .
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      # BACKUP_SCHEDULE: '0 * * * *'  # Hourly
      # PRUNE_SCHEDULE: '0 14 * * 0'  # Sunday midnight, AEST. Use '' to disable.
      PGHOST:
      PGPASSWORD:
      # PGPORT: 5432
      PGUSER:
      # RESTIC_KEEP_HOURLY: 24
      # RESTIC_KEEP_DAILY: 7
      # RESTIC_KEEP_WEEKLY: 4
      # RESTIC_KEEP_MONTHLY: 12
      # RESTIC_KEEP_YEARLY: 7
      RESTIC_PASSWORD:
      RESTIC_REPOSITORY:
    image: ghcr.io/higgs01/restic-pg-dump-docker
    restart: always
